"""Domain-owned contracts implemented by infrastructure adapters."""
from typing import Any, Protocol

Document = dict[str, Any]


class DuplicateRecordError(Exception):
    """A repository uniqueness constraint rejected a write."""


class DocumentRepository(Protocol):
    def find(self, collection: str, **query: Any) -> list[Document]: ...
    def get(self, collection: str, **query: Any) -> Document | None: ...
    def put(self, collection: str, doc: Document) -> Document: ...
    def delete(self, collection: str, **query: Any) -> int: ...
    def consume(self, collection: str, id: str) -> Document | None:
        """Atomically return and delete a document; only one caller can consume it."""
        ...
    def close(self) -> None: ...


class TokenProvider(Protocol):
    def token(self, uid: str, kind: str, seconds: int) -> str: ...
    def decode(self, value: str, kind: str) -> Document: ...


class PasswordHasher(Protocol):
    @property
    def dummy_hash(self) -> str:
        """Hash of an unknown random password for timing-safe missing-user checks."""
        ...
    def hash(self, value: str) -> str: ...
    def verify(self, value: str, hashed: str) -> bool: ...
